apiVersion: apps/v1
kind: Deployment
metadata:
  name: country-lookup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: country-lookup
  template:
    metadata:
      labels:
        app: country-lookup
    spec:
      containers:
      - name: country-lookup
        image: prasadtakale/country_lookup_api:latest
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: country-lookup
spec:
  selector:
    app: country-lookup
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
